/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as OcorrenciasRouteImport } from './routes/ocorrencias'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as EpisRouteImport } from './routes/epis'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as AcessosRouteImport } from './routes/acessos'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciasRoute = OcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisRoute = EpisRouteImport.update({
  id: '/epis',
  path: '/epis',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessosRoute = AcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/cameras': typeof CamerasRoute
  '/epis': typeof EpisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/cameras': typeof CamerasRoute
  '/epis': typeof EpisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/cameras': typeof CamerasRoute
  '/epis': typeof EpisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessos'
    | '/cameras'
    | '/epis'
    | '/notificacoes'
    | '/ocorrencias'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessos'
    | '/cameras'
    | '/epis'
    | '/notificacoes'
    | '/ocorrencias'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/acessos'
    | '/cameras'
    | '/epis'
    | '/notificacoes'
    | '/ocorrencias'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessosRoute: typeof AcessosRoute
  CamerasRoute: typeof CamerasRoute
  EpisRoute: typeof EpisRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OcorrenciasRoute: typeof OcorrenciasRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencias': {
      id: '/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof OcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epis': {
      id: '/epis'
      path: '/epis'
      fullPath: '/epis'
      preLoaderRoute: typeof EpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessos': {
      id: '/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessosRoute: AcessosRoute,
  CamerasRoute: CamerasRoute,
  EpisRoute: EpisRoute,
  NotificacoesRoute: NotificacoesRoute,
  OcorrenciasRoute: OcorrenciasRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
